on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tonypai/summary-gpt-bot:$(echo $GITHUB_REF | rev | cut -d/ -f1 | rev)

    - name: Docker login
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        TAG_NAME=$(echo $GITHUB_REF | rev | cut -d/ -f1 | rev)
        docker push tonypai/summary-gpt-bot:$TAG_NAME
        docker tag tonypai/summary-gpt-bot:$TAG_NAME tonypai/summary-gpt-bot:latest
        docker push tonypai/summary-gpt-bot:latest
